/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Kotlovan(props) {
  const { nodes, materials } = useGLTF("/models/kotlovan_b.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kotlovan_Evro_Lipki_1.geometry}
          material={materials.Kotlovan_Evro_Lipki}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kotlovan_Evro_Lipki_2.geometry}
          material={materials.Kotlovan_Evro_Lipki1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kotlovan_Evro_Lipki_3.geometry}
          material={materials.Kotlovan_Evro_Lipki2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kotlovan_Evro_Lipki_4.geometry}
          material={materials.Kotlovan_Evro_Lipki3}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/kotlovan_b.glb");
